commands:
  01_update_package_list:
    command: apt-get update
  02_install_php_pear:
    command: apt-get install -y php-pear php-dev
  03_install_libmemcached_php:
    command: apt-get install -y libmemcached-dev
  05_run_nigbinary_install:
    command: pecl install igbinary
  05_run_memcached_install:
    command: pecl install -D 'enable-memcached-igbinary="yes"' memcached
  07_enable_igbinary:
    command: echo "extension=\"igbinary.so\""  > $(php -r "echo(PHP_CONFIG_FILE_SCAN_DIR);")/45-igbinary.ini
  08_enable_memcached:
    command: echo "extension=memcached.so"  > $(php -r "echo(PHP_CONFIG_FILE_SCAN_DIR);")/50-memcached.ini
